<?php
	CREATE TABLE USER_TRAVEL(
		user_id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
		user_name VARCHAR(20) NOT NULL,
		passward VARCHAR(20) NOT NULL,
		email VARCHAR(20) NOT NULLL
	)
	
CREATE TABLE TRAVEL_INFO(
  travel_id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  from_to VARCHAR(20) NOT NULL,
  to_from VARCHAR(20) NOT NULL,
  vehicle VARCHAR(20) NOT NULL,
  people INT(5) UNSIGNED NOT NULL,
  period INT(5) UNSIGNED NOT NULL,
  departure VARCHAR(10) NOT NULL,
  user_id INT(5) UNSIGNED NOT NULL
)

	
	CREATE TABLE ORDER_HISTORY(
  travel_id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  from_to VARCHAR(20) NOT NULL,
  to_from VARCHAR(20) NOT NULL,
  vehicle VARCHAR(20) NOT NULL,
  people INT(5) UNSIGNED NOT NULL,
  period INT(5) UNSIGNED NOT NULL,
  departure VARCHAR(10) NOT NULL,
  user_id INT(5) UNSIGNED NOT NULL
)
?>